// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from protos/protocol.proto</summary>
public static partial class ProtocolReflection
{

    #region Descriptor
    /// <summary>File descriptor for protos/protocol.proto</summary>
    public static pbr::FileDescriptor Descriptor
    {
        get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolReflection()
    {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
              "ChVwcm90b3MvcHJvdG9jb2wucHJvdG8iKQoGVmVjdG9yEgkKAXgYASABKAIS",
              "CQoBeRgCIAEoAhIJCgF6GAMgASgCIhQKEkMyU19JY2VKb2luUmVxdWVzdCKJ",
              "AQoYQzJTX0ljZVBsYXllck1vdmVSZXF1ZXN0EhAKCHBsYXllcklkGAEgASgF",
              "EhkKCHBvc2l0aW9uGAIgASgLMgcuVmVjdG9yEhcKBnZlY3RvchgDIAEoCzIH",
              "LlZlY3RvchIQCghyb3RhdGlvbhgEIAEoAhIVCgVzdGF0ZRgFIAEoDjIGLlN0",
              "YXRlIowBCh5TMkNfSWNlUGxheWVyU3Bhd25Ob3RpZmljYXRpb24SEAoIcGxh",
              "eWVySWQYASABKAUSEgoKcGxheWVyVHlwZRgCIAEoBRIZCghwb3NpdGlvbhgD",
              "IAEoCzIHLlZlY3RvchIXCgZ2ZWN0b3IYBCABKAsyBy5WZWN0b3ISEAoIcm90",
              "YXRpb24YBSABKAIi2AEKHVMyQ19JY2VQbGF5ZXJNb3ZlTm90aWZpY2F0aW9u",
              "EjoKB3BsYXllcnMYASADKAsyKS5TMkNfSWNlUGxheWVyTW92ZU5vdGlmaWNh",
              "dGlvbi5QbGF5ZXJEYXRhGnsKClBsYXllckRhdGESEAoIcGxheWVySWQYASAB",
              "KAUSGQoIcG9zaXRpb24YAiABKAsyBy5WZWN0b3ISFwoGdmVjdG9yGAMgASgL",
              "MgcuVmVjdG9yEhAKCHJvdGF0aW9uGAQgASgCEhUKBXN0YXRlGAUgASgOMgYu",
              "U3RhdGUijQIKCkdhbWVQYWNrZXQSLQoOaWNlSm9pblJlcXVlc3QYASABKAsy",
              "Ey5DMlNfSWNlSm9pblJlcXVlc3RIABI5ChRpY2VQbGF5ZXJNb3ZlUmVxdWVz",
              "dBgDIAEoCzIZLkMyU19JY2VQbGF5ZXJNb3ZlUmVxdWVzdEgAEkUKGmljZVBs",
              "YXllclNwYXduTm90aWZpY2F0aW9uGAUgASgLMh8uUzJDX0ljZVBsYXllclNw",
              "YXduTm90aWZpY2F0aW9uSAASQwoZaWNlUGxheWVyTW92ZU5vdGlmaWNhdGlv",
              "bhgLIAEoCzIeLlMyQ19JY2VQbGF5ZXJNb3ZlTm90aWZpY2F0aW9uSABCCQoH",
              "cGF5bG9hZCokCgVTdGF0ZRIICgRJRExFEAASCAoETU9WRRABEgcKA0RJRRAC",
              "YgZwcm90bzM="));
        descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
            new pbr::FileDescriptor[] { },
            new pbr::GeneratedClrTypeInfo(new[] { typeof(global::State), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Vector), global::Vector.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::C2S_IceJoinRequest), global::C2S_IceJoinRequest.Parser, null, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::C2S_IcePlayerMoveRequest), global::C2S_IcePlayerMoveRequest.Parser, new[]{ "PlayerId", "Position", "Vector", "Rotation", "State" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2C_IcePlayerSpawnNotification), global::S2C_IcePlayerSpawnNotification.Parser, new[]{ "PlayerId", "PlayerType", "Position", "Vector", "Rotation" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2C_IcePlayerMoveNotification), global::S2C_IcePlayerMoveNotification.Parser, new[]{ "Players" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::S2C_IcePlayerMoveNotification.Types.PlayerData), global::S2C_IcePlayerMoveNotification.Types.PlayerData.Parser, new[]{ "PlayerId", "Position", "Vector", "Rotation", "State" }, null, null, null, null)}),
          new pbr::GeneratedClrTypeInfo(typeof(global::GamePacket), global::GamePacket.Parser, new[]{ "IceJoinRequest", "IcePlayerMoveRequest", "IcePlayerSpawnNotification", "IcePlayerMoveNotification" }, new[]{ "Payload" }, null, null, null)
            }));
    }
    #endregion

}
#region Enums
public enum State
{
    [pbr::OriginalName("IDLE")] Idle = 0,
    [pbr::OriginalName("MOVE")] Move = 1,
    [pbr::OriginalName("DIE")] Die = 2,
}

#endregion

#region Messages
public sealed partial class Vector : pb::IMessage<Vector>
{
    private static readonly pb::MessageParser<Vector> _parser = new pb::MessageParser<Vector>(() => new Vector());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Vector> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector(Vector other) : this()
    {
        x_ = other.x_;
        y_ = other.y_;
        z_ = other.z_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector Clone()
    {
        return new Vector(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X
    {
        get { return x_; }
        set
        {
            x_ = value;
        }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y
    {
        get { return y_; }
        set
        {
            y_ = value;
        }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Z
    {
        get { return z_; }
        set
        {
            z_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as Vector);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Vector other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
        if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
        if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
        if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
        if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
        if (X != 0F)
        {
            output.WriteRawTag(13);
            output.WriteFloat(X);
        }
        if (Y != 0F)
        {
            output.WriteRawTag(21);
            output.WriteFloat(Y);
        }
        if (Z != 0F)
        {
            output.WriteRawTag(29);
            output.WriteFloat(Z);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(output);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (X != 0F)
        {
            size += 1 + 4;
        }
        if (Y != 0F)
        {
            size += 1 + 4;
        }
        if (Z != 0F)
        {
            size += 1 + 4;
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Vector other)
    {
        if (other == null)
        {
            return;
        }
        if (other.X != 0F)
        {
            X = other.X;
        }
        if (other.Y != 0F)
        {
            Y = other.Y;
        }
        if (other.Z != 0F)
        {
            Z = other.Z;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                case 13:
                    {
                        X = input.ReadFloat();
                        break;
                    }
                case 21:
                    {
                        Y = input.ReadFloat();
                        break;
                    }
                case 29:
                    {
                        Z = input.ReadFloat();
                        break;
                    }
            }
        }
    }

}

/// <summary>
/// 게임 참가 
/// </summary>
public sealed partial class C2S_IceJoinRequest : pb::IMessage<C2S_IceJoinRequest>
{
    private static readonly pb::MessageParser<C2S_IceJoinRequest> _parser = new pb::MessageParser<C2S_IceJoinRequest>(() => new C2S_IceJoinRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2S_IceJoinRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2S_IceJoinRequest()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2S_IceJoinRequest(C2S_IceJoinRequest other) : this()
    {
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2S_IceJoinRequest Clone()
    {
        return new C2S_IceJoinRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as C2S_IceJoinRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(C2S_IceJoinRequest other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(output);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(C2S_IceJoinRequest other)
    {
        if (other == null)
        {
            return;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }

}

/// <summary>
/// 플레이어 이동 
/// </summary>
public sealed partial class C2S_IcePlayerMoveRequest : pb::IMessage<C2S_IcePlayerMoveRequest>
{
    private static readonly pb::MessageParser<C2S_IcePlayerMoveRequest> _parser = new pb::MessageParser<C2S_IcePlayerMoveRequest>(() => new C2S_IcePlayerMoveRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2S_IcePlayerMoveRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2S_IcePlayerMoveRequest()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2S_IcePlayerMoveRequest(C2S_IcePlayerMoveRequest other) : this()
    {
        playerId_ = other.playerId_;
        position_ = other.position_ != null ? other.position_.Clone() : null;
        vector_ = other.vector_ != null ? other.vector_.Clone() : null;
        rotation_ = other.rotation_;
        state_ = other.state_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2S_IcePlayerMoveRequest Clone()
    {
        return new C2S_IcePlayerMoveRequest(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private int playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerId
    {
        get { return playerId_; }
        set
        {
            playerId_ = value;
        }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 2;
    private global::Vector position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vector Position
    {
        get { return position_; }
        set
        {
            position_ = value;
        }
    }

    /// <summary>Field number for the "vector" field.</summary>
    public const int VectorFieldNumber = 3;
    private global::Vector vector_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vector Vector
    {
        get { return vector_; }
        set
        {
            vector_ = value;
        }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 4;
    private float rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Rotation
    {
        get { return rotation_; }
        set
        {
            rotation_ = value;
        }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 5;
    private global::State state_ = global::State.Idle;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::State State
    {
        get { return state_; }
        set
        {
            state_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as C2S_IcePlayerMoveRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(C2S_IcePlayerMoveRequest other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (PlayerId != other.PlayerId) return false;
        if (!object.Equals(Position, other.Position)) return false;
        if (!object.Equals(Vector, other.Vector)) return false;
        if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Rotation, other.Rotation)) return false;
        if (State != other.State) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (PlayerId != 0) hash ^= PlayerId.GetHashCode();
        if (position_ != null) hash ^= Position.GetHashCode();
        if (vector_ != null) hash ^= Vector.GetHashCode();
        if (Rotation != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Rotation);
        if (State != global::State.Idle) hash ^= State.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
        if (PlayerId != 0)
        {
            output.WriteRawTag(8);
            output.WriteInt32(PlayerId);
        }
        if (position_ != null)
        {
            output.WriteRawTag(18);
            output.WriteMessage(Position);
        }
        if (vector_ != null)
        {
            output.WriteRawTag(26);
            output.WriteMessage(Vector);
        }
        if (Rotation != 0F)
        {
            output.WriteRawTag(37);
            output.WriteFloat(Rotation);
        }
        if (State != global::State.Idle)
        {
            output.WriteRawTag(40);
            output.WriteEnum((int)State);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(output);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (PlayerId != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerId);
        }
        if (position_ != null)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
        }
        if (vector_ != null)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vector);
        }
        if (Rotation != 0F)
        {
            size += 1 + 4;
        }
        if (State != global::State.Idle)
        {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)State);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(C2S_IcePlayerMoveRequest other)
    {
        if (other == null)
        {
            return;
        }
        if (other.PlayerId != 0)
        {
            PlayerId = other.PlayerId;
        }
        if (other.position_ != null)
        {
            if (position_ == null)
            {
                Position = new global::Vector();
            }
            Position.MergeFrom(other.Position);
        }
        if (other.vector_ != null)
        {
            if (vector_ == null)
            {
                Vector = new global::Vector();
            }
            Vector.MergeFrom(other.Vector);
        }
        if (other.Rotation != 0F)
        {
            Rotation = other.Rotation;
        }
        if (other.State != global::State.Idle)
        {
            State = other.State;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                case 8:
                    {
                        PlayerId = input.ReadInt32();
                        break;
                    }
                case 18:
                    {
                        if (position_ == null)
                        {
                            Position = new global::Vector();
                        }
                        input.ReadMessage(Position);
                        break;
                    }
                case 26:
                    {
                        if (vector_ == null)
                        {
                            Vector = new global::Vector();
                        }
                        input.ReadMessage(Vector);
                        break;
                    }
                case 37:
                    {
                        Rotation = input.ReadFloat();
                        break;
                    }
                case 40:
                    {
                        State = (global::State)input.ReadEnum();
                        break;
                    }
            }
        }
    }

}

/// <summary>
/// 플레이어 스폰 위치 
/// </summary>
public sealed partial class S2C_IcePlayerSpawnNotification : pb::IMessage<S2C_IcePlayerSpawnNotification>
{
    private static readonly pb::MessageParser<S2C_IcePlayerSpawnNotification> _parser = new pb::MessageParser<S2C_IcePlayerSpawnNotification>(() => new S2C_IcePlayerSpawnNotification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S2C_IcePlayerSpawnNotification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public S2C_IcePlayerSpawnNotification()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public S2C_IcePlayerSpawnNotification(S2C_IcePlayerSpawnNotification other) : this()
    {
        playerId_ = other.playerId_;
        playerType_ = other.playerType_;
        position_ = other.position_ != null ? other.position_.Clone() : null;
        vector_ = other.vector_ != null ? other.vector_.Clone() : null;
        rotation_ = other.rotation_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public S2C_IcePlayerSpawnNotification Clone()
    {
        return new S2C_IcePlayerSpawnNotification(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private int playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerId
    {
        get { return playerId_; }
        set
        {
            playerId_ = value;
        }
    }

    /// <summary>Field number for the "playerType" field.</summary>
    public const int PlayerTypeFieldNumber = 2;
    private int playerType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerType
    {
        get { return playerType_; }
        set
        {
            playerType_ = value;
        }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Vector position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vector Position
    {
        get { return position_; }
        set
        {
            position_ = value;
        }
    }

    /// <summary>Field number for the "vector" field.</summary>
    public const int VectorFieldNumber = 4;
    private global::Vector vector_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vector Vector
    {
        get { return vector_; }
        set
        {
            vector_ = value;
        }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 5;
    private float rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Rotation
    {
        get { return rotation_; }
        set
        {
            rotation_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as S2C_IcePlayerSpawnNotification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(S2C_IcePlayerSpawnNotification other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (PlayerId != other.PlayerId) return false;
        if (PlayerType != other.PlayerType) return false;
        if (!object.Equals(Position, other.Position)) return false;
        if (!object.Equals(Vector, other.Vector)) return false;
        if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Rotation, other.Rotation)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (PlayerId != 0) hash ^= PlayerId.GetHashCode();
        if (PlayerType != 0) hash ^= PlayerType.GetHashCode();
        if (position_ != null) hash ^= Position.GetHashCode();
        if (vector_ != null) hash ^= Vector.GetHashCode();
        if (Rotation != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Rotation);
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
        if (PlayerId != 0)
        {
            output.WriteRawTag(8);
            output.WriteInt32(PlayerId);
        }
        if (PlayerType != 0)
        {
            output.WriteRawTag(16);
            output.WriteInt32(PlayerType);
        }
        if (position_ != null)
        {
            output.WriteRawTag(26);
            output.WriteMessage(Position);
        }
        if (vector_ != null)
        {
            output.WriteRawTag(34);
            output.WriteMessage(Vector);
        }
        if (Rotation != 0F)
        {
            output.WriteRawTag(45);
            output.WriteFloat(Rotation);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(output);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (PlayerId != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerId);
        }
        if (PlayerType != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerType);
        }
        if (position_ != null)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
        }
        if (vector_ != null)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vector);
        }
        if (Rotation != 0F)
        {
            size += 1 + 4;
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(S2C_IcePlayerSpawnNotification other)
    {
        if (other == null)
        {
            return;
        }
        if (other.PlayerId != 0)
        {
            PlayerId = other.PlayerId;
        }
        if (other.PlayerType != 0)
        {
            PlayerType = other.PlayerType;
        }
        if (other.position_ != null)
        {
            if (position_ == null)
            {
                Position = new global::Vector();
            }
            Position.MergeFrom(other.Position);
        }
        if (other.vector_ != null)
        {
            if (vector_ == null)
            {
                Vector = new global::Vector();
            }
            Vector.MergeFrom(other.Vector);
        }
        if (other.Rotation != 0F)
        {
            Rotation = other.Rotation;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                case 8:
                    {
                        PlayerId = input.ReadInt32();
                        break;
                    }
                case 16:
                    {
                        PlayerType = input.ReadInt32();
                        break;
                    }
                case 26:
                    {
                        if (position_ == null)
                        {
                            Position = new global::Vector();
                        }
                        input.ReadMessage(Position);
                        break;
                    }
                case 34:
                    {
                        if (vector_ == null)
                        {
                            Vector = new global::Vector();
                        }
                        input.ReadMessage(Vector);
                        break;
                    }
                case 45:
                    {
                        Rotation = input.ReadFloat();
                        break;
                    }
            }
        }
    }

}

/// <summary>
/// 플레이어들 위치 알림 
/// </summary>
public sealed partial class S2C_IcePlayerMoveNotification : pb::IMessage<S2C_IcePlayerMoveNotification>
{
    private static readonly pb::MessageParser<S2C_IcePlayerMoveNotification> _parser = new pb::MessageParser<S2C_IcePlayerMoveNotification>(() => new S2C_IcePlayerMoveNotification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S2C_IcePlayerMoveNotification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public S2C_IcePlayerMoveNotification()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public S2C_IcePlayerMoveNotification(S2C_IcePlayerMoveNotification other) : this()
    {
        players_ = other.players_.Clone();
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public S2C_IcePlayerMoveNotification Clone()
    {
        return new S2C_IcePlayerMoveNotification(this);
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::S2C_IcePlayerMoveNotification.Types.PlayerData> _repeated_players_codec
        = pb::FieldCodec.ForMessage(10, global::S2C_IcePlayerMoveNotification.Types.PlayerData.Parser);
    private readonly pbc::RepeatedField<global::S2C_IcePlayerMoveNotification.Types.PlayerData> players_ = new pbc::RepeatedField<global::S2C_IcePlayerMoveNotification.Types.PlayerData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::S2C_IcePlayerMoveNotification.Types.PlayerData> Players
    {
        get { return players_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as S2C_IcePlayerMoveNotification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(S2C_IcePlayerMoveNotification other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (!players_.Equals(other.players_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        hash ^= players_.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
        players_.WriteTo(output, _repeated_players_codec);
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(output);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        size += players_.CalculateSize(_repeated_players_codec);
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(S2C_IcePlayerMoveNotification other)
    {
        if (other == null)
        {
            return;
        }
        players_.Add(other.players_);
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                case 10:
                    {
                        players_.AddEntriesFrom(input, _repeated_players_codec);
                        break;
                    }
            }
        }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the S2C_IcePlayerMoveNotification message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types
    {
        public sealed partial class PlayerData : pb::IMessage<PlayerData>
        {
            private static readonly pb::MessageParser<PlayerData> _parser = new pb::MessageParser<PlayerData>(() => new PlayerData());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<PlayerData> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor
            {
                get { return global::S2C_IcePlayerMoveNotification.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor
            {
                get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public PlayerData()
            {
                OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public PlayerData(PlayerData other) : this()
            {
                playerId_ = other.playerId_;
                position_ = other.position_ != null ? other.position_.Clone() : null;
                vector_ = other.vector_ != null ? other.vector_.Clone() : null;
                rotation_ = other.rotation_;
                state_ = other.state_;
                _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public PlayerData Clone()
            {
                return new PlayerData(this);
            }

            /// <summary>Field number for the "playerId" field.</summary>
            public const int PlayerIdFieldNumber = 1;
            private int playerId_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int PlayerId
            {
                get { return playerId_; }
                set
                {
                    playerId_ = value;
                }
            }

            /// <summary>Field number for the "position" field.</summary>
            public const int PositionFieldNumber = 2;
            private global::Vector position_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Vector Position
            {
                get { return position_; }
                set
                {
                    position_ = value;
                }
            }

            /// <summary>Field number for the "vector" field.</summary>
            public const int VectorFieldNumber = 3;
            private global::Vector vector_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Vector Vector
            {
                get { return vector_; }
                set
                {
                    vector_ = value;
                }
            }

            /// <summary>Field number for the "rotation" field.</summary>
            public const int RotationFieldNumber = 4;
            private float rotation_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public float Rotation
            {
                get { return rotation_; }
                set
                {
                    rotation_ = value;
                }
            }

            /// <summary>Field number for the "state" field.</summary>
            public const int StateFieldNumber = 5;
            private global::State state_ = global::State.Idle;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::State State
            {
                get { return state_; }
                set
                {
                    state_ = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other)
            {
                return Equals(other as PlayerData);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(PlayerData other)
            {
                if (ReferenceEquals(other, null))
                {
                    return false;
                }
                if (ReferenceEquals(other, this))
                {
                    return true;
                }
                if (PlayerId != other.PlayerId) return false;
                if (!object.Equals(Position, other.Position)) return false;
                if (!object.Equals(Vector, other.Vector)) return false;
                if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Rotation, other.Rotation)) return false;
                if (State != other.State) return false;
                return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode()
            {
                int hash = 1;
                if (PlayerId != 0) hash ^= PlayerId.GetHashCode();
                if (position_ != null) hash ^= Position.GetHashCode();
                if (vector_ != null) hash ^= Vector.GetHashCode();
                if (Rotation != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Rotation);
                if (State != global::State.Idle) hash ^= State.GetHashCode();
                if (_unknownFields != null)
                {
                    hash ^= _unknownFields.GetHashCode();
                }
                return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString()
            {
                return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output)
            {
                if (PlayerId != 0)
                {
                    output.WriteRawTag(8);
                    output.WriteInt32(PlayerId);
                }
                if (position_ != null)
                {
                    output.WriteRawTag(18);
                    output.WriteMessage(Position);
                }
                if (vector_ != null)
                {
                    output.WriteRawTag(26);
                    output.WriteMessage(Vector);
                }
                if (Rotation != 0F)
                {
                    output.WriteRawTag(37);
                    output.WriteFloat(Rotation);
                }
                if (State != global::State.Idle)
                {
                    output.WriteRawTag(40);
                    output.WriteEnum((int)State);
                }
                if (_unknownFields != null)
                {
                    _unknownFields.WriteTo(output);
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize()
            {
                int size = 0;
                if (PlayerId != 0)
                {
                    size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerId);
                }
                if (position_ != null)
                {
                    size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
                }
                if (vector_ != null)
                {
                    size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vector);
                }
                if (Rotation != 0F)
                {
                    size += 1 + 4;
                }
                if (State != global::State.Idle)
                {
                    size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)State);
                }
                if (_unknownFields != null)
                {
                    size += _unknownFields.CalculateSize();
                }
                return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(PlayerData other)
            {
                if (other == null)
                {
                    return;
                }
                if (other.PlayerId != 0)
                {
                    PlayerId = other.PlayerId;
                }
                if (other.position_ != null)
                {
                    if (position_ == null)
                    {
                        Position = new global::Vector();
                    }
                    Position.MergeFrom(other.Position);
                }
                if (other.vector_ != null)
                {
                    if (vector_ == null)
                    {
                        Vector = new global::Vector();
                    }
                    Vector.MergeFrom(other.Vector);
                }
                if (other.Rotation != 0F)
                {
                    Rotation = other.Rotation;
                }
                if (other.State != global::State.Idle)
                {
                    State = other.State;
                }
                _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input)
            {
                uint tag;
                while ((tag = input.ReadTag()) != 0)
                {
                    switch (tag)
                    {
                        default:
                            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                            break;
                        case 8:
                            {
                                PlayerId = input.ReadInt32();
                                break;
                            }
                        case 18:
                            {
                                if (position_ == null)
                                {
                                    Position = new global::Vector();
                                }
                                input.ReadMessage(Position);
                                break;
                            }
                        case 26:
                            {
                                if (vector_ == null)
                                {
                                    Vector = new global::Vector();
                                }
                                input.ReadMessage(Vector);
                                break;
                            }
                        case 37:
                            {
                                Rotation = input.ReadFloat();
                                break;
                            }
                        case 40:
                            {
                                State = (global::State)input.ReadEnum();
                                break;
                            }
                    }
                }
            }

        }

    }
    #endregion

}

public sealed partial class GamePacket : pb::IMessage<GamePacket>
{
    private static readonly pb::MessageParser<GamePacket> _parser = new pb::MessageParser<GamePacket>(() => new GamePacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GamePacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GamePacket()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GamePacket(GamePacket other) : this()
    {
        switch (other.PayloadCase)
        {
            case PayloadOneofCase.IceJoinRequest:
                IceJoinRequest = other.IceJoinRequest.Clone();
                break;
            case PayloadOneofCase.IcePlayerMoveRequest:
                IcePlayerMoveRequest = other.IcePlayerMoveRequest.Clone();
                break;
            case PayloadOneofCase.IcePlayerSpawnNotification:
                IcePlayerSpawnNotification = other.IcePlayerSpawnNotification.Clone();
                break;
            case PayloadOneofCase.IcePlayerMoveNotification:
                IcePlayerMoveNotification = other.IcePlayerMoveNotification.Clone();
                break;
        }

        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GamePacket Clone()
    {
        return new GamePacket(this);
    }

    /// <summary>Field number for the "iceJoinRequest" field.</summary>
    public const int IceJoinRequestFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::C2S_IceJoinRequest IceJoinRequest
    {
        get { return payloadCase_ == PayloadOneofCase.IceJoinRequest ? (global::C2S_IceJoinRequest)payload_ : null; }
        set
        {
            payload_ = value;
            payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.IceJoinRequest;
        }
    }

    /// <summary>Field number for the "icePlayerMoveRequest" field.</summary>
    public const int IcePlayerMoveRequestFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::C2S_IcePlayerMoveRequest IcePlayerMoveRequest
    {
        get { return payloadCase_ == PayloadOneofCase.IcePlayerMoveRequest ? (global::C2S_IcePlayerMoveRequest)payload_ : null; }
        set
        {
            payload_ = value;
            payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.IcePlayerMoveRequest;
        }
    }

    /// <summary>Field number for the "icePlayerSpawnNotification" field.</summary>
    public const int IcePlayerSpawnNotificationFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::S2C_IcePlayerSpawnNotification IcePlayerSpawnNotification
    {
        get { return payloadCase_ == PayloadOneofCase.IcePlayerSpawnNotification ? (global::S2C_IcePlayerSpawnNotification)payload_ : null; }
        set
        {
            payload_ = value;
            payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.IcePlayerSpawnNotification;
        }
    }

    /// <summary>Field number for the "icePlayerMoveNotification" field.</summary>
    public const int IcePlayerMoveNotificationFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::S2C_IcePlayerMoveNotification IcePlayerMoveNotification
    {
        get { return payloadCase_ == PayloadOneofCase.IcePlayerMoveNotification ? (global::S2C_IcePlayerMoveNotification)payload_ : null; }
        set
        {
            payload_ = value;
            payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.IcePlayerMoveNotification;
        }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase
    {
        None = 0,
        IceJoinRequest = 1,
        IcePlayerMoveRequest = 3,
        IcePlayerSpawnNotification = 5,
        IcePlayerMoveNotification = 11,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadOneofCase PayloadCase
    {
        get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPayload()
    {
        payloadCase_ = PayloadOneofCase.None;
        payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as GamePacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GamePacket other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (!object.Equals(IceJoinRequest, other.IceJoinRequest)) return false;
        if (!object.Equals(IcePlayerMoveRequest, other.IcePlayerMoveRequest)) return false;
        if (!object.Equals(IcePlayerSpawnNotification, other.IcePlayerSpawnNotification)) return false;
        if (!object.Equals(IcePlayerMoveNotification, other.IcePlayerMoveNotification)) return false;
        if (PayloadCase != other.PayloadCase) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (payloadCase_ == PayloadOneofCase.IceJoinRequest) hash ^= IceJoinRequest.GetHashCode();
        if (payloadCase_ == PayloadOneofCase.IcePlayerMoveRequest) hash ^= IcePlayerMoveRequest.GetHashCode();
        if (payloadCase_ == PayloadOneofCase.IcePlayerSpawnNotification) hash ^= IcePlayerSpawnNotification.GetHashCode();
        if (payloadCase_ == PayloadOneofCase.IcePlayerMoveNotification) hash ^= IcePlayerMoveNotification.GetHashCode();
        hash ^= (int)payloadCase_;
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
        if (payloadCase_ == PayloadOneofCase.IceJoinRequest)
        {
            output.WriteRawTag(10);
            output.WriteMessage(IceJoinRequest);
        }
        if (payloadCase_ == PayloadOneofCase.IcePlayerMoveRequest)
        {
            output.WriteRawTag(26);
            output.WriteMessage(IcePlayerMoveRequest);
        }
        if (payloadCase_ == PayloadOneofCase.IcePlayerSpawnNotification)
        {
            output.WriteRawTag(42);
            output.WriteMessage(IcePlayerSpawnNotification);
        }
        if (payloadCase_ == PayloadOneofCase.IcePlayerMoveNotification)
        {
            output.WriteRawTag(90);
            output.WriteMessage(IcePlayerMoveNotification);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(output);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (payloadCase_ == PayloadOneofCase.IceJoinRequest)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(IceJoinRequest);
        }
        if (payloadCase_ == PayloadOneofCase.IcePlayerMoveRequest)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(IcePlayerMoveRequest);
        }
        if (payloadCase_ == PayloadOneofCase.IcePlayerSpawnNotification)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(IcePlayerSpawnNotification);
        }
        if (payloadCase_ == PayloadOneofCase.IcePlayerMoveNotification)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(IcePlayerMoveNotification);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GamePacket other)
    {
        if (other == null)
        {
            return;
        }
        switch (other.PayloadCase)
        {
            case PayloadOneofCase.IceJoinRequest:
                if (IceJoinRequest == null)
                {
                    IceJoinRequest = new global::C2S_IceJoinRequest();
                }
                IceJoinRequest.MergeFrom(other.IceJoinRequest);
                break;
            case PayloadOneofCase.IcePlayerMoveRequest:
                if (IcePlayerMoveRequest == null)
                {
                    IcePlayerMoveRequest = new global::C2S_IcePlayerMoveRequest();
                }
                IcePlayerMoveRequest.MergeFrom(other.IcePlayerMoveRequest);
                break;
            case PayloadOneofCase.IcePlayerSpawnNotification:
                if (IcePlayerSpawnNotification == null)
                {
                    IcePlayerSpawnNotification = new global::S2C_IcePlayerSpawnNotification();
                }
                IcePlayerSpawnNotification.MergeFrom(other.IcePlayerSpawnNotification);
                break;
            case PayloadOneofCase.IcePlayerMoveNotification:
                if (IcePlayerMoveNotification == null)
                {
                    IcePlayerMoveNotification = new global::S2C_IcePlayerMoveNotification();
                }
                IcePlayerMoveNotification.MergeFrom(other.IcePlayerMoveNotification);
                break;
        }

        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                case 10:
                    {
                        global::C2S_IceJoinRequest subBuilder = new global::C2S_IceJoinRequest();
                        if (payloadCase_ == PayloadOneofCase.IceJoinRequest)
                        {
                            subBuilder.MergeFrom(IceJoinRequest);
                        }
                        input.ReadMessage(subBuilder);
                        IceJoinRequest = subBuilder;
                        break;
                    }
                case 26:
                    {
                        global::C2S_IcePlayerMoveRequest subBuilder = new global::C2S_IcePlayerMoveRequest();
                        if (payloadCase_ == PayloadOneofCase.IcePlayerMoveRequest)
                        {
                            subBuilder.MergeFrom(IcePlayerMoveRequest);
                        }
                        input.ReadMessage(subBuilder);
                        IcePlayerMoveRequest = subBuilder;
                        break;
                    }
                case 42:
                    {
                        global::S2C_IcePlayerSpawnNotification subBuilder = new global::S2C_IcePlayerSpawnNotification();
                        if (payloadCase_ == PayloadOneofCase.IcePlayerSpawnNotification)
                        {
                            subBuilder.MergeFrom(IcePlayerSpawnNotification);
                        }
                        input.ReadMessage(subBuilder);
                        IcePlayerSpawnNotification = subBuilder;
                        break;
                    }
                case 90:
                    {
                        global::S2C_IcePlayerMoveNotification subBuilder = new global::S2C_IcePlayerMoveNotification();
                        if (payloadCase_ == PayloadOneofCase.IcePlayerMoveNotification)
                        {
                            subBuilder.MergeFrom(IcePlayerMoveNotification);
                        }
                        input.ReadMessage(subBuilder);
                        IcePlayerMoveNotification = subBuilder;
                        break;
                    }
            }
        }
    }

}

#endregion


#endregion Designer generated code
